rate_my_ride/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from ride import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('glasgow/', views.glasgow, name='glasgow'),
    path('edinburgh/', views.edinburgh, name='edinburgh'),
    path('aberdeen/', views.aberdeen, name='aberdeen'),
    path('ride/', include('ride.urls')),
    # The above maps any URLs starting with rate_my_ride/ to be handled by ride.
    path('admin/', admin.site.urls),
    path('accounts/login/', views.user_login, name='login'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

ride/urls.py
from django.urls import path
from ride import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'ride'

urlpatterns = [
    path('', views.home, name='home'),
    path('glasgow/', views.glasgow, name='glasgow'),
    path('edinburgh/', views.edinburgh, name='edinburgh'),
    path('aberdeen/', views.aberdeen, name='aberdeen'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:location>/add_service/', views.add_service, name='add_service'),
    path('<str:location>/<slug:service_name_slug>/', views.show_services, name='show_services'),
    path('<str:location>/<slug:service_name_slug>/add_review', views.add_review, name='add_review'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('restricted/', views.restricted, name='restricted'),
    path('logout/', views.user_logout, name='logout'),
    path('like_review/', views.like_review, name='like_review'),
] 

ride/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class ServicePage(models.Model):

	serviceID = models.AutoField(primary_key=True)
	name = models.CharField(max_length=32)
	location = models.CharField(max_length=32)
	body = models.CharField(max_length=256)
	logo = models.ImageField(upload_to='logo_images', blank=True)
	slug = models.SlugField(unique=True, blank=True)
	views = models.IntegerField(default=0)

	def save(self, *args, **kwargs):
		self.slug = slugify(self.name+"_"+self.location)
		super(ServicePage, self).save(*args, **kwargs)

	def __str__(self): 
		return self.name

class Review(models.Model):

	serviceID = models.ForeignKey(ServicePage, on_delete=models.CASCADE) 
	userID = models.ForeignKey(User, on_delete=models.CASCADE) 

	reviewID = models.AutoField(primary_key=True)
	date = models.DateTimeField(auto_now_add=True)

	location = models.CharField(max_length=32)
	service = models.CharField(max_length=32)
	rating = models.IntegerField(default=0)
	title = models.CharField(max_length=128)
	body = models.CharField(max_length=256)

	likes = models.IntegerField(default=0)

	def __str__(self):
		return self.title

class UserProfile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	accountUser = models.BooleanField(default=True)
	picture = models.ImageField(upload_to='media', blank=True)

	def __str__(self):
		return self.user.username
		

ride/forms.py
from django import forms
from ride.models import Review, ServicePage
from django.contrib.auth.models import User
from ride.models import UserProfile

class ReviewForm(forms.ModelForm):
    
    ratingChoices = [(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')]

    title = forms.CharField(max_length=128, help_text="Please enter a title for your review.")
    rating = forms.ChoiceField(choices=ratingChoices, widget=forms.RadioSelect, help_text="Please select a rating.")
    location = forms.CharField(max_length=32, help_text="Please enter the city you took the taxi from for your review.")
    body = forms.CharField(max_length=256, help_text="Please talk about your experience.")
    service = forms.CharField(max_length=32, help_text="Please enter the name of the taxi service for your review.")
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta:
        # Provide an association between the ModelForm and a model
        model = Review
        fields = ('title', 'rating', 'location', 'body', 'service')

class ServiceForm(forms.ModelForm):

    name = forms.CharField(max_length=32, help_text="Please enter your service name.")
    location = forms.CharField(max_length=32, help_text="Please enter your service location.")
    body = forms.CharField(max_length=256, help_text="Please enter a description of your service.")
    logo = forms.ImageField(label='Upload your logo')
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form.
    class Meta: 
        # Provide an association between the ModelForm and a model
        model = ServicePage
        fields = ('name', 'location', 'body', 'logo')

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    # accountUser = forms.BooleanField(help_text='Please tick for a user account, leave blank for a service account')
    # picture = forms.ImageField(help_text='Upload your Profile Picture')
    class Meta:
        model = UserProfile
        fields = ('accountUser', 'picture',)

ride/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect 
from ride.forms import ServiceForm, ReviewForm, UserForm, UserProfileForm
from ride.models import ServicePage, Review, User, UserProfile
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from datetime import datetime
from django.views import View
from django.utils.decorators import method_decorator
from django.contrib.auth.models import User
from django.contrib import messages
from django.views.decorators.http import require_GET



def home(request):

    response = render(request, 'ride/home.html')
    return response

def glasgow(request):
    service_list = ServicePage.objects.filter(location='Glasgow').order_by('name')

    city_dict = {}
    city_dict['services'] = service_list
    city_dict['location'] = 'Glasgow'

    city_dict['viewed_services'] = ServicePage.objects.filter(location='Glasgow').order_by('-views')[:5]
    city_dict['reviews'] = Review.objects.filter(location='Glasgow').order_by('-likes')[:5]
    
    visitor_cookie_handler(request)

    return render(request, 'ride/glasgow.html', context=city_dict)

def edinburgh(request):
    service_list = ServicePage.objects.filter(location='Edinburgh').order_by('name')

    city_dict = {}
    city_dict['services'] = service_list
    city_dict['location'] = 'Edinburgh'

    city_dict['viewed_services'] = ServicePage.objects.filter(location='Edinburgh').order_by('-views')[:5]
    city_dict['reviews'] = Review.objects.filter(location='Edinburgh').order_by('-likes')[:5]
    
    visitor_cookie_handler(request)
    
    return render(request, 'ride/edinburgh.html', context=city_dict)

def aberdeen(request):
    service_list = ServicePage.objects.filter(location='Aberdeen').order_by('name')

    city_dict = {}
    city_dict['services'] = service_list
    city_dict['location'] = "Aberdeen"

    city_dict['viewed_services'] = ServicePage.objects.filter(location='Aberdeen').order_by('-views')[:5]
    city_dict['reviews'] = Review.objects.filter(location='Aberdeen').order_by('-likes')[:5]
    
    visitor_cookie_handler(request)
    
    return render(request, 'ride/aberdeen.html', context=city_dict)

def show_services(request, service_name_slug, location):

    context_dict = {}
    
    if request.user.is_authenticated:
        user = request.user
        user_profile = UserProfile.objects.get(user=user)
        account_user = user_profile.accountUser
        context_dict['account_user'] = account_user
    else:
        context_dict['account_user'] = None
    
    try:
        service = ServicePage.objects.get(slug=service_name_slug)
        reviews = Review.objects.filter(service=service,location=location)
        context_dict['reviews'] = reviews
        context_dict['service'] = service
        context_dict['location'] = location
        context_dict['service_name_slug'] = service_name_slug
        service.views += 1
        service.save()
        
    except ServicePage.DoesNotExist:
        context_dict['service'] = None
        context_dict['reviews'] = None
        context_dict['location'] = location
        
    return render(request, 'ride/service.html', context=context_dict)

@login_required
def add_service(request, location):

    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    account_user = user_profile.accountUser

    if account_user == False:
        form = ServiceForm()
        # context_dict = {}
        # context_dict['location'] = location

        if request.method == 'POST':
            form = ServiceForm(request.POST, request.FILES)

            if form.is_valid():
                form.save(commit=True)
                return redirect('/ride/')
            else:
                print(form.errors)
    else:
        return render(request, 'ride/restricted.html')
    
    return render(request, 'ride/add_service.html', {'form': form, 'location': location})

@login_required
def add_review(request, service_name_slug, location):

    user = request.user
    user_profile = UserProfile.objects.get(user=user)
    account_user = user_profile.accountUser

    if account_user == True:
        try:
            # serviceName = service_name_slug
            serviceName = ServicePage.objects.get(slug=service_name_slug)
            serviceID = ServicePage.objects.get(slug=service_name_slug)
            userID = User.objects.get(id=request.user.id)

        except ServicePage.DoesNotExist:
            serviceName = None

        if serviceName is None:
            return redirect('/ride/')

        form = ReviewForm()

        if request.method == 'POST':
            form = ReviewForm(request.POST)

            if form.is_valid():
                if serviceName:
                    review = form.save(commit=False)
                    review.service = serviceName
                    review.userID = userID
                    review.serviceID = serviceID
                    review.views = 0
                    review.save()

                    return redirect(reverse('ride:show_services', kwargs={'service_name_slug':service_name_slug, 'location': location}))
        else:
            print(form.errors)

            context_dict = {'form': form, 'service_name_slug': serviceName, 'location': location}
    else:
        return render(request, 'ride/restricted.html')
    
    return render(request, 'ride/add_review.html', context=context_dict)

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request,'ride/register.html',context = {'user_form': user_form,'profile_form': profile_form,'registered': registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return redirect(reverse('ride:home'))
            else:
                return HttpResponse("Your Ride account is disabled.")
        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")
    else:
        return render(request, 'ride/login.html', {})

@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('ride:home'))

def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val

@login_required
def restricted(request):
    return render(request, 'ride/restricted.html')

def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1'))
    last_visit_cookie = get_server_side_cookie(request,'last_visit',str(datetime.now()))
    last_visit_time = datetime.strptime(last_visit_cookie[:-7],'%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).days > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    
    else:
        request.session['last_visit'] = last_visit_cookie
    request.session['visits'] = visits

def profile(request, username):
    selected_user = User.objects.get(username=username)
    user_profile = UserProfile.objects.get(user=selected_user)

    if request.user == selected_user:
        if request.method == 'POST':
            form = UserProfileForm(request.POST, request.FILES, instance=user_profile)

            if form.is_valid():
                form.save(commit=True)

                messages.success(request, 'Profile updated successfully')

                return HttpResponseRedirect(request.path_info)
        else:
            form = UserProfileForm(instance=user_profile)
    else:
        form = None

    context = {
        'selected_user': selected_user,
        'user_profile': user_profile,
        'form': form,
    }

    return render(request, 'ride/profile.html', context)

@login_required
@require_GET
def like_review(request):
    review_id = request.GET.get('review_id')
    if not review_id:
        return HttpResponse(status=400)
    
    try:
        review = get_object_or_404(Review, id=int(review_id))
    except ValueError:
        return HttpResponse(status=400)

    review.likes += 1
    review.save()
    return HttpResponse(review.likes)
    

templates/ride/add_review.html
{% extends 'ride/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Add a Review
{% endblock %}

{% block body_block %}
</br>
</br>
</br>
</br>
{% if user.is_authenticated %}
    <div class="jumbotron p-4">
        <div class="container">
            <h1 class="jumbotron-heading">Add a Review to {{service_name_slug.name}}</h1>
            <p><a href="javascript:history.back()">Back to {{service_name_slug.name}} page</a></p>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <form id="review_form" enctype="multipart/form-data" method="post" action="{% url 'ride:add_review' location service_name_slug.slug %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
                {% for field in form.visible_fields %}
                    {{ field.errors }}
                    {{ field.help_text }}</br>
                    {{ field }}</br>
                    <div class="p-2"></div>
                {% endfor %}
                    <br />
                    <button class="btn btn-primary" type="submit" name="submit">
                        Create Review
                    </button>
                    <div class="p-5"></div>
            </form>
        </div>
    </div>
{% endif %}
{% endblock %}

templates/ride/add_service.html
{% extends 'ride/base.html' %}
{% load staticfiles %}
{% load static%}

{% block title_block %}
    Add a Service
{% endblock %}

{% block body_block %}
</br>
</br>
</br>
</br>
{% if user.is_authenticated %}
<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Service to {{location}}</h1>
        <p><a href="javascript:history.back()">Back to {{location}} page</a></p>
    </div>
</div>
<div class="container">
    <div class="row">
        <form id="service_form" enctype="multipart/form-data" method="post" action="{% url 'ride:add_service' location %}">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}</br>
                {{ field }}</br>
                <div class="p-2"></div>
            {% endfor %}
                <br />
                <button class="btn btn-primary" type="submit" name="submit">
                        Create Service
                </button>
                <div class="p-5"></div>
        </form>
    </div>
</div>
{% endif %}
{% endblock %}

templates/ride/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load ride_template_tags %} 

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <link rel="icon" href="{% static 'images/taxi.png' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'ride/stylesheet.css' %}">
    <title>
        Rate My Ride - {% block title_block %}Home{% endblock %}
    </title>
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css"
        rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css"
        rel="stylesheet">
</head>
<body>
    <!-- Header nav bar -->
    <header>
        <nav class="navbar navbar-expand-md fixed-top p-0" style="background-color: rgb(164, 194, 244);">
            <img src="{% static 'images/taxi.png' %}" alt="Taxi" class="img-fluid" style="width: 150px; height: auto;">
            <a class="p-2 nav_title nav-link text-dark" href="{% url 'ride:home' %}">Rate My Ride</a>
    
            <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
    
            <div class="collapse navbar-collapse justify-content-end" id="navbarCollapse">
                <ul class="navbar-nav p-4 ">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'ride:profile' user.username %}">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'ride:logout' %}?next=/ride/">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link text-dark" href="{% url 'ride:register' %}">Register Here</a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link text-dark" href="{% url 'ride:login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
    </header>
    
    <!-- Sidebar -->
    <nav class="col-md-2 d-none d-md-block sidebar">
    </br>

        <div class="sidebar-sticky" style="background-color: rgb(201, 218, 248);">
            <ul class="navbar-nav mr-auto p-4">
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'ride:glasgow' %}">Glasgow</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" href="{% url 'ride:edinburgh' %}">Edinburgh</a>
                </li>
                <li class="nav-item ">
                   <a class="nav-link text-dark" href="{% url 'ride:aberdeen' %}">Aberdeen</a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- Background colour -->
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4" style="background-color: rgb(207, 226, 243);">
        {% block body_block %}
        {% endblock %}
    </main>
    <!-- Footer bar -->
    <footer>
        <div class="footerdiv" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            <div class="left">
                &copy; 2023 Rate My Ride
            </div>
            <div class="right">
                <a href="#">Back to top</a>
            </div>
        </div>
    </footer>
    
    <!-- Bootstrap core JavaScript -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script>
        window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')
        </script>
    <script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js">
        </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js">
    </script>
    <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js">
    </script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous"></script>
    <script src="{% static 'js/ride-ajax.js' %}" crossorigin="anonymous"></script>

    </body>
</html>

templates/ride/home.html
{% extends 'ride/base.html' %}

{% load static %}

{% block title_block %}
Home
{% endblock %}

{% block body_block %}
</br>
</br>
<div class="container my-5" >
  <div class="jumbotron bg-light p-4">
    <h1 class="display-4 mb-4">
      {% if user.is_authenticated %}
        Welcome back, {{ user.username }}!
      {% else %}
        Welcome to Rate My Ride!
      {% endif %}
    </h1>
    <p class="lead">
      Rate My Ride is a rating platform that allows you to share your taxi ride experiences with other users. It is an interactive platform in which users can view and like other customers' taxi reviews. Rate My Ride aims to help customers decide what taxi service is best for them and their needs. We provide a list of taxi services in Glasgow, Edinburgh and Aberdeen.
    </p>
  </div>
</div>
<div class="container my-5">
    <h2 class="text-center mb-5">Locations</h2>
    <div class="row">
      <div class="col-md-6 mb-3">
        <img src="{% static 'images/map_of_scotland.png' %}" alt="image" width="100%" style="max-width: 500px;">
      </div>
      <div class="col-md-6">
        <div class="d-flex flex-column">
          <div class="card mb-3" style="background-color: rgb(201, 218, 248);">
            <a href="/ride/glasgow/"></a>
            <div class="card-body">
              <h5 class="card-title">Glasgow</h5>
              <a href="/ride/glasgow/" class="btn btn-primary stretched-link">View Rides in Glasgow</a>
            </div>
          </div>
          <div class="card mb-3" style="background-color: rgb(201, 218, 248);">
            <a href="/ride/edinburgh/"></a>
            <div class="card-body">
              <h5 class="card-title">Edinburgh</h5>
              <a href="/ride/edinburgh/" class="btn btn-primary stretched-link">View Rides in Edinburgh</a>
            </div>
          </div>
          <div class="card mb-3" style="background-color: rgb(201, 218, 248);">
            <a href="/ride/aberdeen/"></a>
            <div class="card-body">
              <h5 class="card-title">Aberdeen</h5>
              <a href="/ride/aberdeen/" class="btn btn-primary stretched-link">View Rides in Aberdeen</a>
            </div>
          </div>
        </div>
      </div>
    </div>
</div>

{% endblock %}

templates/ride/login.html
{% extends 'ride/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
<style>
    .cardcolour {
        background: rgb(74, 134, 232);
    }
</style> 
    <section class="gradient-custom">
        <div class="container py-5 h-50">
        <div class="row d-flex justify-content-center align-items-center h-50">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
            <div class="card cardcolour text-white" style="border-radius: 1rem;">
                <div class="card-body p-5 text-center">
    
                <div class="mb-md-5 mt-md-4 pb-5">
                    <form id="login_form" method="post" action="{% url 'ride:login' %}">
                        {% csrf_token %}
    
                        <h2 class="fw-bold mb-2 text-uppercase">Login to your account</h2>
                        <p class="text-white-50 mb-5">Please enter your login and password!</p>
        
                        <div class="form-outline form-white mb-4">
                            <input type="text" name="username" id="username"value="" size="50" class="form-control form-control-lg"/>
                            <label class="form-label" for="username">Username</label>
                        </div>
        
                        <div class="form-outline form-white mb-4">
                            <input type="text" name="password" id="password"value="" size="50" class="form-control form-control-lg"/>
                            <label class="form-label" for="password">Password</label>
                        </div>
                        <input class="btn btn-outline-light btn-lg px-5" type="submit" value="Login">
                    </form>
    
                </div>
    
                <div>
                    <p class="mb-0">Don't have an account? <a href="{% url 'ride:register' %}" class="text-white-50 fw-bold">Register Here</a>
                    </p>
                </div>
    
                </div>
            </div>
            </div>
        </div>
        </div>
    </section>
{% endblock %}

templates/ride/register.html
{% extends 'ride/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<style>
    .cardcolour {
        background: rgb(74, 134, 232);
    }
</style>
<section class="gradient-custom">
    <div class="container py-5 h-50">
    <div class="row d-flex justify-content-center align-items-center h-50">
        <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card cardcolour text-white" style="border-radius: 1rem;">
            <div class="card-body p-5 text-center">

            <div class="mb-md-5 mt-md-4 pb-5">
                <h2 class="fw-bold mb-2 text-uppercase">Register here!</h2>
                        {% if registered %}
                            <div class="alert alert-success text-center" role="alert">
                                <strong>Thank you for registering!</strong>
                                <a href="{% url 'ride:home' %}" class="alert-link">Return to the homepage.</a>
                            </div>
                        {% else %}
                            <form id="user_form" method="post" action="{% url 'ride:register' %}" enctype="multipart/form-data">
                                {% csrf_token %}
                                <p class="text-white-50 mb-5">Please enter your details!</p>
                                <!-- Display each form -->
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                                <!-- Provide a button to submit the form -->
                                <input class="btn btn-outline-light btn-lg px-5" type="submit" value="Register">
                            </form>
                        {% endif %}
            </div>
            </div>
        </div>
        </div>
    </div>
    </div>
</section>
{% endblock %}

templates/ride/restricted.html
{% extends 'ride/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Restricted Page
{% endblock %}

{% block body_block %}
</br>
</br>

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Restricted Page</h1>
    </div>
</div>
You are not authorised!!!!<br />
{% endblock %}

templates/ride/service.html
{% extends 'ride/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if service %}
        {{ service.name }}
    {% else %}
        Unknown Service
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="container pb-4" style="border-bottom: 2px solid rgb(0, 0, 0);">
        </br>
        </br>
        </br>
        </br>
        <div class="row">
            <div class="col-md-6">
                        {% if service %}
                            
                            <h1>{{ service.name }}</h1>
                            <div>{{service.body}}</div>
                            <br>
                            <p><a href="javascript:history.back()">Back to {{location}} page</a></p>
                            <h2>Reviews</h2>
                            {% if reviews %}
                                {% for review in reviews %}
                                    <div class="card mb-6" style="background-color: rgb(201, 218, 248);">
                                        <div class="card-body">
                                            <div class="review-box" id="review-{{ review.id }}">
                                                <h2><strong>{{ review.title }}</strong></h2>   
                                                <p><strong>Rating:</strong> {{ review.rating }}</p>
                                                <p>{{ review.body }}</p>
                                                <div>
                                                    <strong id="like_count">{{ review.likes }}</strong> likes
                                                    {% if user.is_authenticated %}
                                                        <button id="like_btn" data-reviewid="{{ review.id }}" class="btn btn-primary btn-sm" type="button">
                                                        <span data-feather="thumbs-up"></span>
                                                        Like Review
                                                        </button>
                                                    {% endif %}
                                                </div> 
                                            </div>
                                        </div>
                                    </div>
                                <br>
                                {% endfor %}
                                {% else %}
                                    <strong>No reviews currently in service.</strong>
                                {% endif %}
                                {% if user.is_authenticated %}
                                    <a href="{% url 'ride:add_review' location service.slug %}">Add Review</a> <br />
                                {% endif %}
                        {% else %}
                            The specified service does not exist.
                        {% endif %}
            </div>
            <div class="col-md-6">
                <img src="{{service.logo}}" alt="{{service.name}} logo" width="100%" style="max-width: 150px;">
            </div>
        </div>
    </div>
{% endblock %}